### ISSUE TITLE
Port to coqpp

### ISSUE THREAD

**Issue by ejgallego** [ppedrot/ltac2#83]
"En casa de herrero, cuchillo de palo"

https://github.com/coq/coq/pull/8945

**Comment by ppedrot** [comment]
Yeah I know, but Ltac2 is doing fancy stuff with grammar rules to backtrack on addition of extension points when reverting imports. I could hand-expand the rules but this is ugly, I think I should add a variant of `GRAMMAR EXTEND` to coqpp that uses the synchronized grammar extensions rather than the global ones.

**Comment by ppedrot** [comment]
FTR, the trick we use currently is here: https://github.com/ppedrot/ltac2/blob/master/src/g_ltac2.ml4#L796.

**Comment by ejgallego** [comment]
O_O XD

**Comment by ejgallego** [comment]
Should this be closed @ppedrot ?

**Comment by ppedrot** [comment]
Indeed.
